### ISSUE TITLE
Prevent misconfiguration via `--add` (adding entry with same key)

### ISSUE THREAD

**Issue by oschrenk** [TBS1996/TaleCast#1]
More a tale of a use case than a proper bug, but I thought I post it. Feel free to close it as a configuration issue:

I did
`talecast --add "https://rss.acast.com/offmenu" "Off Menu"`

Then tried (of course I first tried it without the backtrace)

```
RUST_BACKTRACE=1 talecast --print
thread 'main' panicked at /Users/oliver/.cargo/registry/src/index.crates.io-6f17d22bba15001f/talecast-0.1.17/src/config.rs:275:37:
called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: DuplicateTable("Off Menu"), line: Some(3), col: 0, at: Some(52), message: "", key: ["Off Menu"] } }
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: talecast::config::PodcastConfig::load_all
   4: talecast::podcast::Podcast::load_all::{{closure}}
   5: tokio::runtime::runtime::Runtime::block_on
   6: talecast::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

Let's have a look at the config

I assumed it would create an initial `podcasts.yml`  in my `~/.config` but I can't find any configuration files:

```
ls -la ~/.config/talecast/
total 0
drwxr-xr-x   2 oliver  staff    64 Apr 15 16:34 .
drwx------  47 oliver  staff  1504 Apr 15 16:21 ..
```

I looked at https://crates.io/crates/dirs and found out that the `config_dir` is defaulting to `$HOME/Library/Application Support` on macOS. Fair enough. It would be great if the crate would respect `XDG_CONFIG_HOME` even if you are on macOS since I have it set for other applications. 

```
env | grep XDG
XDG_CONFIG_HOME=/Users/oliver/.config
```

But that's ok. 

```
cat /Users/oliver/Library/Application\ Support/talecast/podcasts.toml
["Off Menu"]
url = 'https://rss.acast.com/offmenu'

["Off Menu"]
url = 'https://rss.acast.com/offmenu'
```

It seems, I accidentally added it twice. It might be a better UX to prevent adding a key to my config file.

**Comment by TBS1996** [comment]
Hi, thanks a lot for the great writeup!

I've now ensured it prevents double adding when using --add (and opml imports). (talecast version 0.1.20).  
 
about the config path, it now checks the XDG_CONFIG_HOME variable, and if it's not there, it uses HOME/.config even on mac.

**Comment by oschrenk** [comment]
Neat. Thank you for the work!
