### ISSUE TITLE
Installing via yay AUR package manager

### ISSUE THREAD

**Issue by themarcman314** [TBS1996/TaleCast#4]
I ran into a dependency problem when trying to install via aur.
Cargo worked without any problems though.
Great program overall, search function works well!

**Comment by TBS1996** [comment]
Could you paste the error you're receiving?  
I'm not using arch so I can't trivially check it, someone else is the maintainer of it: https://github.com/TBS1996/TaleCast/pull/3

after you paste it, you can ping him here, and hopefully he will fix it.

Glad you like the program btw! and thank you for bringing this issue to my attention ^^

**Comment by themarcman314** [comment]
During the build process:

```
error: failed to download `autocfg v1.1.0`

Caused by:
  attempting to make an HTTP request, but --frozen was specified
```
And then I get an exit status 4.



Steps to reproduce:
`yay -S talecast-git`

@rukh-debug

**Comment by rukh-debug** [comment]
I have removed the `--frozen` flag and pushed, had the same issue with other package while using --forzen.

I think this should fix the issue you are running into. Can you please verify if its working on your end. 

@themarcman314

**Comment by themarcman314** [comment]
Yep it works @rukh-debug  :)
Awesome!
