### ISSUE TITLE
Possible misconfiguration of  talecast --search and other 

### ISSUE THREAD

**Issue by HirschBerge** [TBS1996/TaleCast#9]
# Information
Distro: Nixos 24.05 Uakari on 64bit Linux
Installation Method: `cargo install talecast`
Version `TaleCast 0.1.31`
Kernel:   6.6.28
# Error
Using talecast --search and selecting an option, it will populate the `~/.config/talecast/podcasts.toml` file like such
```
["\"ITWC\""]
url = "\"https://cybersecuritytoday.libsyn.com/rss\""
```
~~As a sidenote, the options from the search are numbered starting as 0, but when you want to add the 0th option, it will say that 0 is out of bounds and exit, making you +=1  to any selections. Please make these line up~~
When attempting to download  with the generated podcast settings, it will panic.
```
talecast
fetching podcasts...
thread 'main' panicked at /home/hirschy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/talecast-0.1.31/src/utils.rs:103:31:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
When I look at the source code, you're trying to unwrap an error value  from reqwest. It seems that you're maybe passing another error from parsing the incorrect podcasts.toml? I haven't looked into the source that much, but [here](https://github.com/TBS1996/TaleCast/blob/4abb134e0de918fd8580363cf48e10c3cf51d17c/src/utils.rs#L103) is the line of code where it panics
```
pub fn handle_response(response: Result<reqwest::Response, reqwest::Error>) -> reqwest::Response {
    match response {
        Ok(res) => res,
        Err(e) => {
            let url = e.url().unwrap().clone();
           ...
           }
}
```
When removing the odd \"'s from podcasts.toml with `sed -i 's/\\\"//g' ~/.config/talecast/podcasts.toml`
to make it
```
["ITWC"]
url = "https://cybersecuritytoday.libsyn.com/rss"
```
everything works as expected (other than the misaligned numbers with the --search option.
# Oh, but here's another
Well. Almost. Not really
I now get the following:
```
talecast
fetching podcasts...
syncing 1 podcasts
⠤  ITWC    1/100 Cyber Security Today, Week ...  ██████████████░ 57.55 MiB/57.66 MiBthread 'tokio-runtime-worker' panicked at /home/hirschy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/talecast-0.1.31/src/cache.rs:71:40:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Syncing complete!
0 episodes downloaded.
```
with leads us to [here](https://github.com/TBS1996/TaleCast/blob/4abb134e0de918fd8580363cf48e10c3cf51d17c/src/cache.rs#L71C1-L71C49) 

This i'm not sure about, other than you shouldn't use unwrap in production code, at least use .expect() if you don't think it will panic. It makes troubleshooting a lot easier. I thought maybe it didn't like me putting it on my NAS through NFS for some reason, but it didn't like ~/ either. It does make a file  in the ITWC dir, but it's the GUID.mp3 and i can't delete it because it doesn't exist, I guess. I really want to like and use this project, but it's unusable for me.

**Comment by TBS1996** [comment]
Hi, thanks a lot for creating this issue, and sorry about the problems you encountered.

I've fixed and published the misconfiguration from using talecast --search, I accidentally wrote the name of the podcast host instead of the podcast name itself, and messed up the indices. I also strip the quotes properly now. 

about the error on the cached images, I'm not sure why that's happening, it should have written the mimetype to .cache/talecast/mime_types, in the write_image function. I'll look into it now but for now if it doesnt find the mimetype it'll just not add the image. I want to look into adding a logging feature next so this kinda stuff will be easier to debug.  
 

>This i'm not sure about, other than you shouldn't use unwrap in production code, at least use .expect() if you don't think it will panic. It makes troubleshooting a lot easier. I thought maybe it didn't like me putting it on my NAS through NFS for some reason, but it didn't like ~/ either. It does make a file in the ITWC dir, but it's the GUID.mp3 and i can't delete it because it doesn't exist, I guess. I really want to like and use this project, but it's unusable for me.


I'm a bit confused about the GUID.mp3 don't exist so you can't delete it?  do you get any errors here unrelated to the ones you posted above?  
 
anyway i just published also the possibility to set a custom path for partial downloads with the `partial_path`, if it's not set it'll use the `download_path` as before. not sure if that would be helpful.

**Comment by HirschBerge** [comment]
> I'm a bit confused about the GUID.mp3 don't exist so you can't delete it? do you get any errors here unrelated to the ones you posted above?

Yeah, I'm sorry, it's hard to explain accurately. I can see the file with `ls` and file explorers, but if I try to `rm` it, it returns an OS error saying that it doesn't exist. It's similar to how sometimes if you don't have the correct dependencies for running a binary, it will return the same error.
I was able to just remove the parent directory to work around that.

Thank you for looking into this! I will check into the update!

**Comment by HirschBerge** [comment]
Everything is now working as I expect it!
Thanks for such fast turnaround
